# Generated by Django 5.2.15 on 2026-06-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200, verbose_name='Medicine name')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Batch number')),
                ('expiry_date', models.DateField(verbose_name='Expiry date')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('supplier', models.CharField(max_length=200, verbose_name='Supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['expiry_date', 'medicine_name'],
            },
        ),
    ]
